### ISSUE TITLE
Logout users???

### ISSUE THREAD

**Issue by manikmi** [sto/ngx_http_auth_pam_module#12]
Hi,

This is not an issue. But a request.

Can there be an option of logging out the users??

I am using it with my Angularjs app. Can there be a work around to logout users?

Regards,
Manik Mittal

**Comment by ravi-sensify** [comment]
@manikmi, Can you clarify what exactly you mean by "option to logging out the users" ?

**Comment by manikmi** [comment]
Hi Ravi, 
Thankyou for your response.
What I wanted was a quick user login logout solution for my angular js app. I used this package to login the user. But in my angular js app I wanted to give a logout button, which when pressed the user should be logged out from the system. Don't know if it is possible.

**Comment by C-Duv** [comment]
@manikmi Being HTTP auth I guess it's up to the browser to stop sending credentials when user wants to logout.
Some browsers offers a way to disable/remove HTTP auth, some don't :-/

**Comment by sto** [comment]
Basic Auth does not provide a logout mechanism, but you can use a dirty hack like the one described here: http://tuhrig.de/basic-auth-log-out-with-javascript/
In any case, nothing can be done on the module, so I'm closing the bug.

**Comment by rigid** [comment]
i'm logging out of basic authentication by using a location that deletes the "Authorization" header:

```
location /logout {                                                                                                                                                     
            # disable cache                                                                                                                                                    
            add_header Pragma no-cache;                                                                                                                                        
            add_header Cache-Control "private, max-age=0, no-cache";                                                                                                           
                                                                                                                                                                               
            # remove Authorization header                                                                                                                                      
            add_header Authorization "";                                                                                                                                       
                                                                                                                                                                               
            # back to login                                                                                                                                                    
            return 301 https://$server_name/login.html;                                                                                                                        
        }    
```

Not sure about standard conformity but works for me™  ;)
