### ISSUE TITLE
pam_mysql auth get lost after a while

### ISSUE THREAD

**Issue by jadjay** [sto/ngx_http_auth_pam_module#15]
Hi,

# System
```yaml
- OS: CentOS7
- nginx: 1.10.2
- pam: 1.1.8
- mysql:   5.5.56-MariaDB
```

# Configuration
I authenticate with pam_mysql
```pam
auth required pam_mysql.so user=USER passwd=...
account sufficient pam_mysql.so user=USER passwd=...
```
And use the auth_pam module : 
```nginx
auth_pam           "Closed site";
auth_pam_service_name "PAMFILE";
```

# Problem
Everything's run ok, but after a while (hours or days not sure), we get those messages in error.log : 

```log
Can't initialize threads: error 11
Can't initialize threads: error 11
Can't initialize threads: error 11
Can't initialize threads: error 11
Can't initialize threads: error 11
``` 

Each time the user can't get authenticated,

# Workaround
The workaround so fare is to reload nginx,

Any clue on this problem ?

**Comment by mikemol** [comment]
PAM is exercised by libraries loaded into the nginx process. It sounds like you're finding a bug in pam_mysql.

**Comment by jadjay** [comment]
This bug doesn't show up when you increase the number of process for nginx.

I'm sure it's more a nginx bug/trouble than a pam/pam-module one.

**Comment by sto** [comment]
I've seen problems with other buggy pam modules that had to be solved preloading libraries, I don't use libpam-mysql myself, but I don't see how this can be this modules fault, if you find were it fails feel free to reopen the issue and send a patch
