### ISSUE TITLE
auth.log/secure missing rhost ++

### ISSUE THREAD

**Issue by kenshin33** [sto/ngx_http_auth_pam_module#16]
I noticed that resulting logs in /var/log/auth.log on debian (9) system rhost is missing,m like so:

     Feb  9 16:48:57 hostname ker process: pam_krb5(nginx:auth): authentication failure; logname=asd uid=33 euid=33 tty= ruser= rhost=

in contrast a failed ssh login yields this :  

    Feb  8 09:33:06 hostname sshd[14194]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=X.X.X.X  user=root

which is very useful  for a system like fail2ban!

**Comment by sbraz** [comment]
[This may help](https://github.com/sto/ngx_http_auth_pam_module/pull/18): you'll see auth failures in nginx's error log with it.

**Comment by sto** [comment]
Fixed with https://github.com/sto/ngx_http_auth_pam_module/pull/14
