### ISSUE TITLE
nginx 1.14 module is not beeing loaded

### ISSUE THREAD

**Issue by Scriptkiddi** [sto/ngx_http_auth_pam_module#17]
using nginx 1.14 from the ppa:nginx/stable on a ubuntu 16.04 leeds to the module not beeing loaded

**Comment by pimlie** [comment]
Did you add `include /etc/nginx/modules-enabled/*.conf;` to the top of `/etc/nginx/nginx.conf` ?

It seems Ubuntu created the `mods-enabled` directory but doesnt include those configuration files by default. You have to include them yourself.

**Comment by Scriptkiddi** [comment]
I will try with a new installation and reopen this issue if I encounter it again

**Comment by Scriptkiddi** [comment]
you where right
