### ISSUE TITLE
satisfy  any doesnt work

### ISSUE THREAD

**Issue by chdietrich** [sto/ngx_http_auth_pam_module#20]
```
satisfy  any;
allow 1.2.3.4;
deny all;

auth_pam    "Login with your pam account.";
auth_pam_service_name   "nginx";
```

..should prompt for password except if remote ip is "1.2.3.4". This seems to work with auth_basic but not with auth_pam.

**Comment by elemoine** [comment]
I am also interested to know if the `satisfy` directive is supported.

**Comment by sto** [comment]
I believe the changes on #25 fix this issue, if they don't feel free to reopen the issue.
