### ISSUE TITLE
work with google-authenticator-libpam

### ISSUE THREAD

**Issue by kuznetcoff777** [sto/ngx_http_auth_pam_module#27]
Made location with
`    auth_pam              "Secure Zone";
    auth_pam_service_name "nginx";
`

Made qr-key /root/.google_authenticator and checked it via sshd, works, asks otp and then password of user.

Made /etc/pam.d/nginx:
auth       required     pam_google_authenticator.so debug secret=/root/.google_authenticator

When entring location on borwser - asks basic auth, entring root and OTP - and no luck, in logs.

`2022/12/30 16:30:14 [error] 1765471#1765471: *1 PAM: user 'root' - not authenticated: Authentication failure, client: 1.1.1.1, server: localhost, request: "GET / HTTP/1.1", host: "2.2.2.2"
`

If i do something wrong and it cannot work as i expect?

**Comment by kuznetcoff777** [comment]
Ticket related to this one https://github.com/google/google-authenticator-libpam/issues/221

```
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: start of google_authenticator for "test"
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: Secret file permissions are 0400. Allowed permissions are 0600
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: "/var/google/test/.google_authenticator" read
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: shared secret in "/var/google/test/.google_authenticator" processed
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: google_authenticator for host "10.137.85.102"
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: no scratch code used from "/var/google/test/.google_authenticator"
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: Accepted google_authenticator for test
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: "/var/google/test/.google_authenticator" written
Dec 30 17:27:14 test-oracle-linux-8 nginx(pam_google_authenticator)[1765713]: debug: end of google_authenticator for "test". Result: Success
```
So google says success, but location still gives me 401 and asks for login-password

**Comment by kuznetcoff777** [comment]
chmod 600 "/var/google/test/.google_authenticator"

after that i login-otp

```
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: start of google_authenticator for "test"
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: Secret file permissions are 0600. Allowed permissions are 0600
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: "/var/google/test/.google_authenticator" read
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: shared secret in "/var/google/test/.google_authenticator" processed
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: google_authenticator for host "1.1.1.1"
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: no scratch code used from "/var/google/test/.google_authenticator"
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: Accepted google_authenticator for test
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: "/var/google/test/.google_authenticator" written
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: end of google_authenticator for "test". Result: Success
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: start of google_authenticator for "test"
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: Secret file permissions are 0400. Allowed permissions are 0600
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: "/var/google/test/.google_authenticator" read
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: shared secret in "/var/google/test/.google_authenticator" processed
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: google_authenticator for host "10.137.85.102"
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: no scratch code used from "/var/google/test/.google_authenticator"
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: Trying to reuse a previously used time-based code. ("/var/google/test/.google_authenticator")Retry again in 30 seconds. Warning! This might mean, you are currently subject to a man-in-the-middle attack.
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: Invalid verification code for test
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: "/var/google/test/.google_authenticator" written
Dec 30 17:44:37 test-oracle-linux-8 nginx(pam_google_authenticator)[1765833]: debug: end of google_authenticator for "test". Result: Authentication failure
```
In the beginning 0600 and Result: Success

After that it begin another check it is 0400 and Result: Authentication failure

Any thoughts how come?

**Comment by sto** [comment]
This does not seem related to the nginx module, but the pam authentication module; keep in mind that the pam module is called for each request done to nginx and each call is a blocking call (bad for nginx model, but pam works that way).

If you are loading a page that needs 20 files and the pam module does not support catching it will try to authenticate on all the calls and it looks that the current implementation does not support that (I might be wrong, have not reviewed nor tried the module you are using).

For this kind of problem maybe the http_auth_pam module approach is not the best one, in fact lately I almost never use this module, when I need external authentication/authorization with `nginx` I build a simple web app and call it with the [auth_request](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html) module (if you need catching it can be implemented on the app using something like memcached or redis)

As I don't see how to fix your problem on this module, I'm closing the issue with this comment.

**Comment by sto** [comment]
> /etc/pam.d/nginx: `auth required pam_google_authenticator.so debug user=nginx secret=/var/google/${USER}/.google_authenticator`
> 
> ```
> ==> /var/log/secure <==
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: start of google_authenticator for "test"
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: Secret file permissions are 0600. Allowed permissions are 0600
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: "/var/google/test/.google_authenticator" read
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: shared secret in "/var/google/test/.google_authenticator" processed
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: google_authenticator for host "1.1.1.1"
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: no scratch code used from "/var/google/test/.google_authenticator"
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: Accepted google_authenticator for test
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: "/var/google/test/.google_authenticator" written
> Dec 31 00:42:13 test-oracle-linux-8 nginx(pam_google_authenticator)[1766125]: debug: end of google_authenticator for "test". Result: Success
> ```
> 
> ```
> ==> /var/log/nginx/error.log <==
> 2022/12/31 00:42:13 [error] 1766125#1766125: *1 PAM: user 'test' - invalid account: Authentication failure, client: 10.137.85.102, server: localhost, request: "GET / HTTP/1.1", host: "10.138.17.161"
> ```
> 
> So, google says Succes, but in nginx i see "user 'test' - invalid account"
> 
> How come?

That error is from the PAM `account` configuration, if you are not using it at least add a the following settings on your pam configuration:

```
# No action required for account management
account   required pam_permit.so
```
